[build-system]
requires = ["setuptools>=61.2", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rh5py"
dynamic = ["version"]
description = "rh5py"
readme = "README.md"
requires-python = ">=3.11"
license = { file = "./LICENSE" }
keywords = ["hdf5"]
authors = [
  { name = "Ming Yang", email = "ymviv@qq.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = [
    "blosc2>=2.7.1",
    "requests>=2.32.3",
    "numpy",
    "pydantic",
]

[project.urls]
Documentation = "https://github.com/vivym/rh5py#readme"
Issues = "https://github.com/vivym/rh5py/issues"
Source = "https://github.com/vivym/rh5py"

[tool.setuptools.dynamic]
version = {attr = "rh5py.__version__"}
